### ISSUE TITLE
Formatierungssymbole sind nach Rückkehr vom Bearbeitungsverlauf nicht mehr vorhanden 

### ISSUE THREAD

**Issue by DZenker** [jrocho/ILIAS-Etherpad-Lite-Plugin#10]
...und auch die Symbole für den "Bearbeitungsverlauf" und "Version speichern" fehlen:
[https://dlsmedia.lecturecast.de/engage/theodul/ui/core.html?id=5fb5084b-34eb-4697-b690-7344213f9d90](https://dlsmedia.lecturecast.de/engage/theodul/ui/core.html?id=5fb5084b-34eb-4697-b690-7344213f9d90)
Nach einem Page Refresh ist alles wieder normal.

ILIAS Version 5.3.11 und EtherpadLite Plugin Version 1.4.2.

**Comment by jrocho** [comment]
Danke für den Hinweis! Bitte die v1.4.1 verwenden. Die v1.4.2 ist noch in Bearbeitung da bei mir auch noch nicht alles 100% funktioniert.

**Comment by DZenker** [comment]
Hi Jan,

danke für das schnelle Feedback. Wir haben jetzt auf 1.4.0 gedowngraded (1.4.1 ist hier nicht getaggt), da tritt das Problem aber leider immer noch auf...

**Comment by jrocho** [comment]
Ich bekomme es hier weder mit dem aktuellen Chrome noch mit Firefox unter ILIAS 5.3 reproduziert (Plugin v1.4.2). Tauchen bei euch in der Error Console irgendwelche Fehlermeldungen auf?

**Comment by DZenker** [comment]
Bei mir tritt das bei beiden Browsern auf, auch auf unterschiedlichen Rechnern. Habe es mal mit den Entwicklertools gescheckt: Ursache ist, dass für sämtliche Links in der Symbol- bzw. Menüleiste das display-Attribut auf "none" gesetzt ist (siehe Screenshot).

![etherpad - fehlende symbole](https://user-images.githubusercontent.com/5229751/50980401-e8b2fd00-14f8-11e9-953c-e3ced867811e.png)

**Comment by jrocho** [comment]
Hallo Dietmar, ich habe das Problem bei mir heute reproduzieren und lösen können. Die Verbesserungen im iPad Support sind jetzt auch für das erste komplett. Für die 1.4.2 habe ich noch keinen Tag gemacht - den mache ich erst wenn es jetzt auch bei euch funktioniert. Deshalb bitte einmal die aktuelle Version aus der "master" Branch testen.

**Comment by jrocho** [comment]
Ganz vergessen .... du musst die pad.js und die pad.css (neu) durch die entsprechenden neuen pad.js.sample und pad.css.sample ersetzen/ergänzen.

**Comment by DZenker** [comment]
Hi Jan,

hat ein bisschen gedauert: haben jetzt wieder den master integriert und die beiden o.g. Dateien ersetzt - nun funktioniert alles bestens!!

Vielen Dank für Deine schnelle Hilfe und Problemlösung. Ist ein tolles Tool, auf das einige Dozierende bei uns schon lange warten, und die Integration in ILIAS ist prima umgesetzt!

LG,
Dietmar
