### ISSUE TITLE
Missing support for etherpad-lite 1.8.6

### ISSUE THREAD

**Issue by pascalseeland** [jrocho/ILIAS-Etherpad-Lite-Plugin#13]
Trying to connect to an etherpad-lite 1.8.6 results with the message: Du hast keine Berechtigung, um auf dieses Pad zuzugreifen. (No access to this pad)

**Comment by bogenschlag** [comment]
(With the `etherpadlite_1-4` branch, since we’re still on ILIAS 5.4 and intend to skip 6.)

**Comment by jrocho** [comment]
Apparently there are some major authentification changes, even though I can't really find anything in the API documentation which would directly effect this in the plugin sense. Most compatibility changes however seem to be related to Etherpad 1.8.7. Right now I'm using it with 1.8.4 but I will look into this.

**Comment by jrocho** [comment]
This is a bug in the Etherpad Lite server which was introduced on 1.8.6. Please wait for >1.8.6 to be release or use and older version. It's working again with the current development branch.
