### ISSUE TITLE
Löschung von Pads (ILIAS-Objekte vs. EP-Server)?

### ISSUE THREAD

**Issue by bogenschlag** [jrocho/ILIAS-Etherpad-Lite-Plugin#4]
Mehr eine Frage als ein Issue: Wenn ein Pad-Objekt in ILIAS gelöscht wird, triggert das auch die Löschung des zugehörigen Pads auf dem EP-Server? – Und wenn nein, ginge das grundsätzlich (und wie viel würde es kosten 😉)?

**Comment by jrocho** [comment]
Um endlich mal darauf zu Antworten... 🙄  ... Pads werden vom EP-Server gelöscht und wenn das erfolgreich war anschließend in ILIAS. Wobei natürlich erst in den Papierkorb geschoben werden (falls aktiviert) und erst beim Löschen aus dem Papierkorb auch vom Server verschwinden.
