### ISSUE TITLE
Catch exception when deleting pad that no longer exists

### ISSUE THREAD

**Issue by corro** [jrocho/ILIAS-Etherpad-Lite-Plugin#7]
I'm not completely sure whether this is an issue with the plugin or the "Empty Trash" cron job implementation, but when there are pads referenced in ILIAS that no longer exist in Etherpad itself, the following error is thrown during the cron job:

> INFO: ilObjEtherpadLite::doDelete:220 Delete Pad ID: g.QOSwyaHiDeD3KnVa$p5cojrsdkxv33rca2ws0
> WARNING: ilErrorHandling::{closure}:50 PHP Error: padID does not exist in /var/www/ilias/Customizing/global/plugins/Services/Repository/RepositoryObject/EtherpadLite/libs/etherpad-lite-client/etherpad-lite-client.php on line 101

After this exception, further execution of the cron job is aborted, leading to the rather misleading state "Cron job deactivated because it has been inactive for 3 hours".

In my opinion, this exception should be catched by the plugin and the reference in ILIAS should be deleted nevertheless.

**Comment by jrocho** [comment]
I just took a look at it. When I remove a pad (which is deleted on the pad server) manually using "Repository Trash and Permission" in the administration it throws the exception but ILIAS handles it. 
When I do the same thing using the cron job I get the same effect that you are seeing and I get Whoops page (executing it manually). So apparently the cronjob can't really handle the exception that occurs and fails. 
I need to investigate this further. 

The exception is thrown by the library which I'm using to interface with the Etherpad API. I plan to switch to a different library in the future which is based on a newer version  of the Etherpad API which would allow new features like 'Copy' to be implemented. But even that library is not complete and I would need to add some functionality  to it and rewrite multiple parts of the plugin. But that would still not help when it throws an exception and the cronjob can't handle it.

(Testing on ILIAS 5.2)

**Comment by jrocho** [comment]
This issue is solved now thanks to @theodortruffer !
